const ARTICLE_TYPES = {
    LOAD_ARTICLES: 'LOAD_ARTICLES',
    LOAD_ARTICLES_SUCCESS: 'LOAD_ARTICLES_SUCCESS',
    LOAD_ARTICLES_ERROR: 'LOAD_ARTICLES_ERROR',
    REQUEST_CREATE_ARTICLE: 'REQUEST_CREATE_ARTICLE',
    CREATE_ARTICLE_SUCCESS: 'CREATE_ARTICLE_SUCCESS',
    CREATE_ARTICLES_ERROR: 'CREATE_ARTICLES_ERROR',
    GET_ARTICLE: 'GET_ARTICLE',
    GET_ARTICLE_SUCCESS: 'GET_ARTICLE_SUCCESS',
    GET_ARTICLE_ERROR: 'GET_ARTICLE_ERROR',
};

export { ARTICLE_TYPES };
