export const FETCH_WHISKIES = 'FETCH_WHISKYS';
export const FETCH_WHISKIES_SUCCESS = 'FETCH_WHISKYS_SUCCESS';
export const FETCH_WHISKIES_FAILURE = 'FETCH_WHISKYS_FAILURE';

const WHISKY_TYPES = {
    FETCH_WHISKIES: 'FETCH_WHISKIES',
    FETCH_WHISKIES_SUCCESS: 'FETCH_WHISKIES_SUCCESS',
    FETCH_WHISKIES_FAILURE: 'FETCH_WHISKIES_FAILURE',
};

export { WHISKY_TYPES };
